import React, { useState } from 'react';
import { generateImage } from '../../services/geminiService';
import LoadingSpinner from '../LoadingSpinner';

const ImageGenPanel: React.FC = () => {
    const [prompt, setPrompt] = useState<string>('');
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string>('');

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!prompt.trim()) {
            setError('Harap masukkan deskripsi gambar.');
            return;
        }

        setIsLoading(true);
        setError('');
        setGeneratedImage(null);

        try {
            const result = await generateImage(prompt);
            if (result) {
                setGeneratedImage(result);
            } else {
                setError('Gagal membuat gambar. Silakan coba deskripsi yang berbeda.');
            }
        } catch (err) {
            console.error(err);
            setError('Terjadi kesalahan yang tidak terduga. Silakan coba lagi.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="flex flex-col h-full items-center p-4 bg-gray-800/50 rounded-lg shadow-xl">
            <h2 className="text-xl font-semibold mb-4 text-blue-300">Generator Gambar AI</h2>
            
            <form onSubmit={handleSubmit} className="w-full max-w-lg space-y-4 mb-6">
                <textarea
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    placeholder="Deskripsikan gambar yang ingin Anda buat..."
                    className="w-full p-3 bg-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-white resize-none"
                    rows={3}
                    disabled={isLoading}
                />
                <button
                    type="submit"
                    disabled={isLoading || !prompt.trim()}
                    className="w-full p-3 bg-blue-600 rounded-md text-white font-semibold hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                    {isLoading ? 'Membuat...' : 'Buat Gambar'}
                </button>
            </form>

            {error && <p className="mb-4 text-red-400">{error}</p>}

            <div className="w-full max-w-lg flex-1 flex justify-center items-center bg-gray-900/50 rounded-lg overflow-hidden">
                {isLoading ? (
                    <LoadingSpinner size="h-12 w-12" />
                ) : generatedImage ? (
                    <img src={generatedImage} alt="Generated by AI" className="object-contain max-w-full max-h-full" />
                ) : (
                    <p className="text-gray-500">Gambar yang dihasilkan akan muncul di sini</p>
                )}
            </div>
        </div>
    );
};

export default ImageGenPanel;
